general {
    lock_cmd = pidof hyprlock || hyprlock
    ceck_color = rgba(0, 0, 0, 0)
    before_sleep_cmd = playerctl pause ; loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

Listener {
    timeout = 300 # 5min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330 # 5.5min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 900 # 30min
    on-timeout = systemctl suspend
}
